FROM ler0ever/evdev.spacemacs:latest
MAINTAINER Everette Rong (https://rongyi.blog)

# git
COPY git/gitconfig $HOME/.gitconfig
COPY git/gitignore_global $HOME/.gitignore_global

# AMP
COPY amp/config.yml $HOME/.config/amp/config.yml
COPY amp/Dracula.tmTheme $HOME/.config/amp/themes/Dracula.tmTheme
RUN sudo chown -R everette:everette $HOME/.config/amp && sudo chmod -R 777 $HOME/.config/amp 

# go
ENV GOPATH /workdir
ENV GOBIN /usr/local/bin

# ssh
COPY ssh $HOME/.ssh
RUN sudo chown -R everette:everette $HOME/.ssh && sudo chmod 600 $HOME/.ssh/config
# RUN ssh-keyscan github.com > $HOME/.ssh/known_hosts

# colors
COPY xterm-256color-italic.terminfo $XDG_CONFIG_HOME/xterm-256color-italic.terminfo
RUN tic $XDG_CONFIG_HOME/xterm-256color-italic.terminfo
# RUN curl -fsSL https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh | bash

# tmux config
COPY tmux/tmux.conf.local $HOME/.tmux.conf.local
COPY tmux/tmux.conf $HOME/.tmux.conf

# zsh
RUN sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
COPY zsh/zshrc $HOME/.zshrc
COPY zsh/void-mod.zsh-theme $HOME/.oh-my-zsh/custom/themes/

# node
RUN yarn global add eslint prettier && yarn cache clean

COPY vim/ctags $HOME/.ctags

RUN git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf \
 && ~/.fzf/install --bin
