#!/bin/bash

main() {
  [  -z "$EDN"  ] && export EDN="EvDev_Container" || echo "Starting $EDN"
  docker run \
      -it \
      --rm \
      --name "$EDN" \
      --hostname "$EDN" \
      --volume "$PWD":/workdir \
      --volume "$HOME":/home/host \
      --volume ~/.ssh/id_rsa:/home/everette/.ssh/id_rsa \
      ler0ever/evdev "$@"
}

main "$@"
